import type { Express } from "express";
import { createServer, type Server } from "http";
import mongoose from "mongoose";
import { storage } from "./storage";
import { api } from "@shared/routes";
import { z } from "zod";
import { RoomModel, UserModel } from "./models/mongo"; // Import for seeding and user lookup
import { sendComplaintToDepartment, sendComplaintAcceptanceToUser, sendComplaintResolutionEmail, sendComplaintAssignmentEmail, getEmailLog } from "./services/email";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<void> {
  // Setup Session & Auth for Local Development
  const session = (await import("express-session")).default;
  const MemoryStore = (await import("memorystore")).default(session);

  app.use(
    session({
      cookie: { maxAge: 86400000 },
      store: new MemoryStore({ checkPeriod: 86400000 }),
      resave: false,
      saveUninitialized: false,
      secret: "keyboard cat",
    })
  );

  // Auth Routes
  app.get("/api/auth/user", (req, res) => {
    if ((req.session as any).user) {
      return res.json((req.session as any).user);
    }
    res.status(401).send("Unauthorized");
  });

  app.post("/api/register", async (req, res) => {
    const { email, firstName, lastName, password } = req.body;

    // Check if user exists
    const existingUser = await storage.getUserByEmail(email);
    if (existingUser) {
      return res.status(409).json({ message: "User already exists" });
    }

    // ID generation handled by Mongo (or manual if we want custom ID format like 'user-...')
    // Using Mongo default IDs is better, but schema interface expects string. 
    // Mongoose helper toJSON converts _id to id string automatically.

    try {
      const newUser = await storage.createUser({
        // id will be auto-generated by mongo if omitted, but our interface might require it if explicit
        // Let's pass undefined for ID to let mongo handle it, but types might complain.
        // Actually storage.createUser calls UserModel.create(user). 
        // We can pass everything except ID.
        email,
        username: email,
        firstName: firstName || "User",
        lastName: lastName || "",
        role: email === "suvethavenkatesan@gmail.com" ? "admin" : "user",
        password: password
      } as any);

      (req.session as any).user = newUser;
      res.status(201).json(newUser);
    } catch (e) {
      console.error("Registration failed:", e);
      res.status(500).json({ message: "Registration failed" });
    }
  });

  app.post("/api/login", async (req, res) => {
    const { email, password } = req.body;

    const user = await storage.getUserByEmail(email);

    if (!user) {
      return res.status(401).json({ message: "Invalid credentials" }); // User not found
    }

    // Simple password check (in real app use bcrypt.compare)
    if (user.password !== password) {
      return res.status(401).json({ message: "Invalid credentials" });
    }

    (req.session as any).user = user;
    res.json(user);
  });

  app.post("/api/logout", (req, res) => {
    req.session.destroy(() => {
      res.sendStatus(200);
    });
  });

  // Complaints
  app.get(api.complaints.list.path, async (req, res) => {
    const user = (req.session as any).user;
    const userId = user?.role === "admin" ? undefined : user?.id;
    const complaints = await storage.getComplaints(userId);
    res.json(complaints);
  });

  app.post(api.complaints.create.path, async (req, res) => {
    try {
      const input = api.complaints.create.input.parse(req.body);
      const user = (req.session as any).user;
      if (!user) return res.status(401).send("Unauthorized");

      const complaint = await storage.createComplaint({ ...input, userId: user.id });
      await sendComplaintToDepartment(
        input.title,
        input.description,
        input.department,
        user.email,
        user.id
      );
      await sendComplaintAcceptanceToUser(
        user.email,
        input.title,
        String(complaint.id)
      );

      res.status(201).json(complaint);
    } catch (err) {
      if (err instanceof z.ZodError) {
        return res.status(400).json({
          message: err.errors[0].message,
          field: err.errors[0].path.join('.'),
        });
      }
      throw err;
    }
  });

  app.get(api.complaints.stats.path, async (req, res) => {
    const stats = await storage.getComplaintStats();
    res.json(stats);
  });

  app.post("/api/complaints/:id/resolve", async (req, res) => {
    const user = (req.session as any).user;
    if (!user || user.role !== "admin") {
      return res.status(403).send("Unauthorized");
    }

    const { comment } = req.body;
    const { id } = req.params;

    try {
      const complaint = await storage.resolveComplaint(id, comment);

      // Fetch User using storage abstraction (works seamlessly across Mongo and In-Memory)
      const complaintUser = await storage.getUserById(complaint.userId);
      const recipientEmail = complaintUser?.email || complaint.userId;

      if (recipientEmail) {
        await sendComplaintResolutionEmail(
          recipientEmail,
          complaint.title,
          String(complaint.id),
          comment
        );
      }

      res.json(complaint);
    } catch (e) {
      console.error("Failed to resolve complaint:", e);
      res.status(500).json({ message: "Failed to resolve complaint" });
    }
  });

  app.post("/api/complaints/:id/assign", async (req, res) => {
    const user = (req.session as any).user;
    if (!user || user.role !== "admin") {
      return res.status(403).send("Unauthorized");
    }

    const { comment } = req.body;
    const { id } = req.params;

    try {
      const complaint = await storage.getComplaintById(id);

      if (!complaint) {
        return res.status(404).send("Complaint not found");
      }

      await sendComplaintAssignmentEmail(
        complaint.department,
        complaint.title,
        comment,
        String(complaint.id)
      );

      res.json({ message: "Assignment email sent successfully" });
    } catch (e) {
      console.error("Failed to assign complaint:", e);
      res.status(500).json({ message: "Failed to assign complaint" });
    }
  });

  // Rooms
  app.get(api.rooms.list.path, async (req, res) => {
    const rooms = await storage.getRooms();
    res.json(rooms);
  });

  // Bookings
  app.get(api.bookings.list.path, async (req, res) => {
    const user = (req.session as any).user;
    const userId = user?.role === "admin" ? undefined : user?.id;

    const bookings = await storage.getBookings(userId);
    res.json(bookings);
  });

  app.post(api.bookings.create.path, async (req, res) => {
    try {
      const input = api.bookings.create.input.parse({
        ...req.body,
        startTime: new Date(req.body.startTime),
        endTime: new Date(req.body.endTime)
      });
      const user = (req.session as any).user;
      if (!user) return res.status(401).send("Unauthorized");

      // Check availability
      const isAvailable = await storage.checkAvailability(
        input.roomId,
        input.startTime,
        input.endTime
      );

      if (!isAvailable) {
        return res.status(409).json({ message: "Room is occupied for the selected time slot." });
      }

      const booking = await storage.createBooking({ ...input, userId: user.id });
      res.status(201).json(booking);
    } catch (err) {
      if (err instanceof z.ZodError) {
        return res.status(400).json({
          message: err.errors[0].message,
          field: err.errors[0].path.join('.'),
        });
      }
      throw err;
    }
  });

  // Email log endpoint (for demo/testing)
  app.get("/api/email-log", async (req, res) => {
    res.json(getEmailLog());
  });

  // Seed Data (if Mongo is connected and empty)
  if (mongoose.connection && mongoose.connection.readyState === 1) {
    const rooms = await storage.getRooms();
    if (rooms.length === 0) {
      console.log("Seeding rooms in MongoDB...");
      await RoomModel.insertMany([
        {
          _id: 1,
          name: "C V Raman (8)",
          capacity: 8,
          location: "Hyderabad",
          building: "NOB",
          floor: "3rd Floor",
          amenities: ["Projector", "Table"],
          isOccupied: false
        },
        {
          _id: 2,
          name: "Mother Teresa (15)",
          capacity: 15,
          location: "Hyderabad",
          building: "NOB",
          floor: "3rd Floor",
          amenities: ["Video Conf", "Whiteboard"],
          isOccupied: false
        },
        {
          _id: 3,
          name: "APJ Abdul Kalam (12)",
          capacity: 12,
          location: "Hyderabad",
          building: "SOB",
          floor: "2nd Floor",
          amenities: ["Projector", "Wifi"],
          isOccupied: false
        },
      ]);
      console.log("Rooms seeded in MongoDB.");
    }
  }
}

